#'\code{phylo.average.brlen}
#'
#'@details uses the treefiles produced byt the PAMML software and a dated tree to calculate the average 
#'branch length of sister clades and the distance from their most recent common ancestor MRCA
#'@param phy a subtree with a root edge
#'@return A double representing the phylogenetic average of branch lengths for the clade.
#'
#'
#'@author Andrew Ritchie, 2021
#'
#'@examples
#' test.tree <- read.tree(read.tree(text= "(((A:1, B:1):1, C:1):1, D:1);"))
#' plot(test.tree)
#' test.subtree <- drop.tip(test.tree, "D", root.edge = 1)
#' plot(test.subtree, root.edge=T)
#' av.blen <- phylo.average.brlen(test.subtree)
#' av.blen # should be 2.5
#'
#'@import ape
#'

phylo.average.brlen <- function (phy){
  
  po <- reorder.phylo(phy, order = "postorder")
  
  br <- array(0, dim = Nnode(phy) + Ntip(phy))
  
  for (i in 1:Nedge(phy))
  {
    br[po$edge[i, 1]] <- br[po$edge[i, 1]] + (po$edge.length[i] + br[po$edge[i, 2]])/2
  }
  
  root.edge.length = ifelse(is.null(phy$root.edge), 0, phy$root.edge)
  singleton = ifelse(Ntip(phy) == 1, 2, 1) 
  
  return (br[Ntip(phy) + 1] * singleton + root.edge.length)
  
}


# Usage: subtree.mean.branch.length <- branch_length_treefiles (dir, Subtrees_note_list)
# 
# Parameters: This function takes a directory with the subtrees from PAML and the output of the Find_Outgroups() function
# Value: a list of average branch lengths of the tree files
# 
# Example:
# 
# test.tree <- read.tree(read.tree(text= "(((A:1, B:1):1, C:1):1, D:1);"))
# plot(test.tree)
# test.subtree <- drop.tip(test.tree, "D", root.edge = 1)
# plot(test.subtree, root.edge=T)
# av.blen <- phylo.average.brlen(test.subtree)
# av.blen # should be 2.5


#'\code{branch_length_treefiles}
#'
#'@details uses the treefiles produced byt the PAML software and a dated tree to calculate the average 
#'branch length of sister clades and the distance from their most recent common ancestor MRCA
#'@param dir The directory with the tree files produced by PAML
#'@param dat_tree a directory of the dated tree file
#'@param @param info_table a table with as many rows as the tips in the tree file
#'and corresponding names and at least one column to group them
#'@param subtrees_list the lsit of subtrees generated by the 
#'find_Outgroups() function
#'@param subtrees_note a matrix of information about the sister 
#'pairs and outgroups generated by the find_Outgroups() function
#'@return The function will return a dataframe that indicates for each sister pair (rows) the name, 
#'size in tips and average branch length and finally the distance of the most common recent ancestor
#'
#'
#'@author Matteo Spatuzzi, 2022
#'
#'@import phylotools
#'@import stringr
#'@import seqinr
#'
#'

# dir = "mit"
# dat_tree = dated_Tree_sqm
# info_tab = classification_sqm
# Subtrees_note_list = Subtrees_note_list_mit
# Phy_genes_reduced = Phy_genes_reduced_mit

branch_length_treefiles <- function(dir = getwd(), dat_tree = getwd(), info_tab,  Subtrees_note_list, Phy_genes_reduced){
  
  #Set directory
  library(ape)
  WorkingDirectory <- dir
  setwd(WorkingDirectory)
  classification <- info_tab
  
  #get filenames of all subtrees from PAML
  files <- system2("ls", stdout = TRUE)
  # Filter filenames and read the tree files
  tree_files <- files[which(substr(files,str_length(files)-3 ,str_length(files) ) == ".tre")]
  Tree_list <- lapply(tree_files, FUN = read.tree)
  
  # Get dated tree file
  dated_Tree <- dat_tree
  
  #Iterate over every sister pair
  # Initialize empty table to fill with results
  br_res <- data.frame(matrix(nrow = dim(Subtrees_note_list[[2]])[1], ncol = 7))
  
  for (tree in 1:dim(Subtrees_note_list[[2]])[1]){
    
    #Initialize empty result vector for iteration
    br_vec <- c()
    
    #Extract sister pair names
    sister_pair <- Subtrees_note_list[[2]][tree,c(1,2)]
    
    #Extract equivalent tree from the tree files as the indexes might be different
    tree_indexes <- lapply(sister_pair, function(x) which(!is.na(str_locate(tree_files, x))[,1]))
    tree_index <- intersect(tree_indexes[[1]],tree_indexes[[2]])
    
    if(length(tree_index) == 1){
      
      Tree <- Tree_list[[tree_index]]
      
      ### Extract general information about the whole pair
      # Tree_length
      Tree$edge.length[which( Tree$edge[,1] == length(Tree$tip.label)+1)]
      length(Tree$tip.label)
      
      # Remove outgroup from subtree
      # Establish the number of the root node in reduced subtree
      sister_pair_tips <- rownames(Phy_genes_reduced[which(Phy_genes_reduced[,2] %in% sister_pair),])
      Tree <- keep.tip(Tree, sister_pair_tips[which(sister_pair_tips %in% Tree$tip.label)])
      root_id <- length(Tree$tip.label)+1
      
      #Establish time at which point the two sister diverged by averaging across dated trees
      lengths <- c(rep(NA, length(dated_Tree)/100))
      for (i in 1:((length(dated_Tree))/100)) {
        
        dated_Tree_red <- keep.tip(dated_Tree[[i]], sister_pair_tips)
        lengths[i] <- dist.nodes(dated_Tree_red)[1,length(dated_Tree_red$tip.label)+1]
        print(i)
      }
      length_avg <- mean(lengths)
      
      ### Extract general information about the individual sisters
      
      ## Sister 1
      
      # Trim subtree to only sister 1
      sister_pair_tips1 <- rownames(Phy_genes_reduced[which(Phy_genes_reduced[,2] == sister_pair[1]),])
      sister_pair_tips1 <- sister_pair_tips1[which(sister_pair_tips1 %in% Tree$tip.label)]
      Tree_red1 <- keep.tip(Tree, sister_pair_tips1)
      
      # Calculate average branch length unless there is only one tip, just take the root to tip distance
      if(length(Tree_red1$tip.label) == 1){
        
        br_len1 <- Tree$edge.length[which(Tree$edge[,1] == root_id & Tree$tip.label %in% sister_pair_tips1)]
      }else{
        
        root_id1 <- getMRCA(phy = Tree, tip = sister_pair_tips1)
        root_len1 <- Tree$edge.length[which(Tree$edge[,1] == root_id & Tree$edge[,2] == root_id1)]
        br_len1 <- phylo.average.brlen(Tree_red1) + root_len1
      }
      
      pair1_data <- c(sister_pair[1], length(which(classification$Family == sister_pair[1])), br_len1)
      
      ## Sister 2
      
      # Trim subtree to only sister 2
      sister_pair_tips2 <- rownames(Phy_genes_reduced[which(Phy_genes_reduced[,2] == sister_pair[2]),])
      sister_pair_tips2 <- sister_pair_tips2[which(sister_pair_tips2 %in% Tree$tip.label)]
      Tree_red2 <- keep.tip(Tree, sister_pair_tips2[which(sister_pair_tips2 %in% Tree$tip.label)])
      
      # Calculate average branch length unless there is only one tip, just take the root to tip distance
      if(length(Tree_red2$tip.label) == 1){
        
        br_len2 <- Tree$edge.length[which(Tree$edge[,1] == root_id & Tree$tip.label %in% sister_pair_tips2)]
      }else{
        root_id2 <- getMRCA(Tree,tip = sister_pair_tips2)
        root_len2 <- Tree$edge.length[which(Tree$edge[,1] == root_id & Tree$edge[,2] == root_id2)]
        br_len2 <- phylo.average.brlen(Tree_red2) + root_len2
      }
      
      pair2_data <- c(sister_pair[2], length(which(classification$Family == sister_pair[2])), br_len2)
      
      # Create final result vector
      # order the two sisters pair by average branch length in decreasing order
      
      pair_data <- cbind(pair1_data, pair2_data)
      order <- order(c(br_len1, br_len2), decreasing = TRUE)
      pair_data_vec <- append(pair_data[,order[1]], pair_data[,order[2]])
      pair_data_vec <- append(pair_data_vec, length_avg)
      
      #Insert in result dataframe
      br_res[tree,] <- pair_data_vec
      rownames(br_res)[tree] <- paste(sister_pair[1], sister_pair[2], sep = "_")
    }else{
      if(length(tree_index) == 0){
        
      }else{
        
        stop("Multiple files per sister pair")
      }
    }
    
  }
  
  
  
  
  colnames(br_res) <- c("Sister_1_Name", "Tips_in_Sister_1", "Sister_1_avg_br_len", "Sister_2_Name", "Tips_in_Sister_2", "Sister_2_avg_br_len", "Pair_MRCA_AgeA" )
  br_res[,2] <- as.numeric(br_res[,2])
  br_res[,3] <- as.numeric(br_res[,3])
  br_res[,5] <- as.numeric(br_res[,5])
  br_res[,6] <- as.numeric(br_res[,6])
  br_res[,7] <- as.numeric(br_res[,7])
  return(br_res)
  
}


#'\code{contrast_calc}
#'
#'@details Calculates the contrast of clade size and average clade branch length from the PAML 
#' output to search for a linear relationship between the two. Can also be used to investigate their
#'dependence from the age of the MRCA (most recent common ancestor)
#' 
#'@param dat a dataframe generated by the branch_length_treefiles function
#'@param subs_vs_age boolean, indicates whether the tests against the age of the MRCA should be run (TRUE) or not (FALSE)
#'@return The function will return a list of the various results 
#'
#'
#'@author Matteo Spatuzzi, 2022
#'
#'@import phylotools
#'@import stringr
#'@import seqinr
#'

contrast_calc <- function(dat, subs_vs_age = FALSE ){
  
  contrast_Nr_species <- apply(dat, 1, function(x) (log(as.numeric(x[2])) - log(as.numeric(x[5])))/sqrt(as.numeric(x[7])) )
  contrast_branch_length <- apply(dat, 1, function(x) (log(as.numeric(x[3])) - log(as.numeric(x[6])))/sqrt(as.numeric(x[7])) )
  
  LM_NSpeciesVsBranchL <-lm(contrast_Nr_species ~ contrast_branch_length)
  L <- list(Species_contrast = contrast_Nr_species, Substitution_contrast = contrast_branch_length, Species_vs_Substitution = LM_NSpeciesVsBranchL )
  names(L) <- c("contrast_Nr_species", "contrast_branch_length", "LM_NSpeciesVsBranchL")
  
  if(subs_vs_age == TRUE){
    LM_BranchLVsMRCAge <-lm(abs(contrast_branch_length) ~ sqrt(dat[,7]))
    L[[4]] <- LM_BranchLVsMRCAge
    names(L)[[4]] <- c("LM_BranchLVsMRCAge")
  }
  
  if(subs_vs_age == TRUE){
    print("Oh yeah")
    LM_NSpeciesVsMRCAge <-lm(abs(contrast_Nr_species) ~ dat[,7])
    L[[5]] <- LM_NSpeciesVsMRCAge
    names(L)[[5]] <- c("LM_NSpeciesVsMRCAge")
  }
  
  return(L)
}

#'\code{evaluate_linear_models}
#'
#'@details reads the results of the contrast_calc and branch_length_treefiles functions and compiles a dataframe of linear model results
#'@param dir the name of the directory to export the results in
#'@param sub_vs_age boolean, indicates whether the tests against the age of the MRCA were run (TRUE) or not (FALSE)
#'@param Base_contrast Output of the contrast_calc function
#'@param Branch_tree_files Output of the branch_length_treefiles function
#'@return Creates a new directory and exports a csv file with the lm coefficients and the plots into it
#'
#'
#'@author Matteo Spatuzzi, 2022
#'


evaluate_linear_models <- function(dir, subs_vs_age, Base_contrast, Branch_tree_files){
  
  result_dir <- dir
  system2("mkdir", args = result_dir)
  setwd(result_dir)
  
  png("SpeciesNrVsBranchLength.png")
  plot(abs(Base_contrast$contrast_Nr_species), 
       Base_contrast$contrast_branch_length,
       main = "SpeciesNr vs BranchLength",
       xlab = "Clade size contrast", 
       ylab = "Branch length contrast"
  )
  Interc <- summary(Base_contrast$LM_NSpeciesVsBranchL)$coefficients[1,1]
  slope <- summary(Base_contrast$LM_NSpeciesVsBranchL)$coefficients[2,1]
  lines(x = c(0,1), y = c(Interc, Interc + slope))
  dev.off()
  
  if(subs_vs_age){
    png("SpeciesNrVsMRCAAge.png")
    plot(sqrt(Branch_tree_files$Pair_MRCA_AgeA), 
         abs(Base_contrast$contrast_branch_length),
         main = "SpeciesNr vs MRCA age",
         xlab = "sqrt(Age of MRCA)", 
         ylab = "Branch length contrast")
    Interc <- summary(Base_contrast$LM_BranchLVsMRCAge)$coefficients[1,1]
    slope <- summary(Base_contrast$LM_BranchLVsMRCAge)$coefficients[2,1]
    lines(x = c(0,10), y = c(Interc, Interc + 10*slope))
    dev.off()
    
    
    png("BranchLengthVsMRCAAge.png")
    plot(sqrt(Branch_tree_files$Pair_MRCA_AgeA), 
         abs(Base_contrast$contrast_Nr_species),
         main = "BranchLength vs MRCA age",
         xlab = "sqrt(Age of MRCA)", 
         ylab = "Clade size contrast")
    Interc <- summary(Base_contrast$LM_NSpeciesVsMRCAge)$coefficients[1,1]
    slope <- summary(Base_contrast$LM_NSpeciesVsMRCAge)$coefficients[2,1]
    lines(x = c(0,10), y = c(Interc, Interc + 10*slope))
    dev.off()
    
    Results_list <- lapply(Base_contrast[3:5], function(x) summary(x)$coefficients)
  }else{
    Results_list <- lapply(Base_contrast[3], function(x) summary(x)$coefficients)
  }
  
  Results_dat <- rbind(Results_list[[1]], Results_list[[2]], Results_list[[3]])
  rownames(Results_dat) <-c("SpeciesNrVsBranchLength_Intercept",
                            "SpeciesNrVsBranchLength_slope",
                            "SpeciesNrVsMRCAAge_Intercept",
                            "SpeciesNrVsMRCAAge_slope",
                            "BranchLengthVsMRCAAge_Intercept",
                            "BranchLengthVsMRCAAge_slope")
  
  
  write.csv(Results_dat, paste(result_dir, "_LM.csv", sep = ""))
}
